/* ============================================================
   CTHULHU ETERNAL — DATA
   Skills, Archetypes, Edges
   ============================================================ */

const ATTRIBUTES = ['STR', 'CON', 'DEX', 'INT', 'POW', 'CHA'];
const ATTRIBUTE_FULL = {
  STR: 'Strength',
  CON: 'Constitution',
  DEX: 'Dexterity',
  INT: 'Intelligence',
  POW: 'Power',
  CHA: 'Charisma',
};

// ── Base Skill Lists ─────────────────────────────────────────

const JAZZ_SKILLS = {
  'Accounting':       10,
  'Alertness':        20,
  'Art':              10,
  'Athletics':        20,
  'Bureaucracy':      10,
  'Charm':            15,
  'Craft':            10,
  'Demolitions':       0,
  'Disguise':         10,
  'Dodge':            30,
  'Drive':            20,
  'Firearms':         20,
  'First Aid':        10,
  'Foreign Language':  0,
  'Heavy Weapons':    10,
  'History':          10,
  'Insight':          20,
  'Intimidate':       15,
  'Law':              10,
  'Library Use':      20,
  'Medicine':          0,
  'Melee Weapons':    30,
  'Military Training': 0,
  'Navigate':         10,
  'Occult':           10,
  'Persuade':         25,
  'Pilot':             0,
  'Psychoanalysis':    0,
  'Psychology':       10,
  'Regional Lore':     0,
  'Ride':             10,
  'Search':           20,
  'Stealth':          10,
  'Surgery':           0,
  'Survival':         10,
  'Swim':             20,
  'Unarmed Combat':   40,
  'Unnatural':         0,
};

const MODERN_SKILLS = Object.assign({}, JAZZ_SKILLS, {
  'Computer Science':  0,
  'Electronics':      10,
  'Forensics':         0,
  'Heavy Machinery':  10,
  'SIGINT':            0,
  'Ride':              5,   // override: less common
});

// ── Archetypes ───────────────────────────────────────────────

const ARCHETYPES = [

  // ── Jazz Age ──────────────────────────────────────────────

  {
    id: 'academic',
    name: 'Academic',
    ages: ['jazz', 'modern'],
    description: 'Scholars and researchers who have devoted themselves to the pursuit of knowledge, often at great personal cost.',
    flavor: '"The library holds more terrors than any dark alley." Your long years among dusty tomes have prepared you—perhaps too well.',
    bonusSkills: ['Accounting', 'History', 'Insight', 'Law', 'Library Use', 'Occult', 'Psychology', 'Search'],
    bonusAmount: 20,
    optionalSkills: ['Art', 'Foreign Language', 'Medicine', 'Psychoanalysis'],
    optionalCount: 2,
    bonds: 4,
    resources: 2,
  },
  {
    id: 'antiquarian',
    name: 'Antiquarian',
    ages: ['jazz'],
    description: 'Collectors and connoisseurs of ancient objects, rare books, and forgotten curiosities from ages best left unremembered.',
    flavor: '"Every object carries the weight of its history." You have handled enough cursed relics to know that some histories are heavier than others.',
    bonusSkills: ['Alertness', 'Art', 'Charm', 'History', 'Insight', 'Library Use', 'Occult', 'Search'],
    bonusAmount: 20,
    optionalSkills: ['Accounting', 'Drive', 'Foreign Language', 'Persuade'],
    optionalCount: 2,
    bonds: 3,
    resources: 3,
  },
  {
    id: 'artist',
    name: 'Artist',
    ages: ['jazz', 'modern'],
    description: 'Creative souls who see the world through a different lens—and who sometimes glimpse things that should remain unseen.',
    flavor: '"Art is the window through which madness peers." Your muse has led you to places most dare not visit even in dreams.',
    bonusSkills: ['Art', 'Charm', 'Craft', 'History', 'Insight', 'Persuade', 'Psychology', 'Search'],
    bonusAmount: 20,
    optionalSkills: ['Foreign Language', 'Occult', 'Stealth', 'Psychoanalysis'],
    optionalCount: 2,
    bonds: 3,
    resources: 1,
  },
  {
    id: 'clergy',
    name: 'Clergy',
    ages: ['jazz'],
    description: 'Men and women of faith who minister to the spiritual needs of their flock—and now face horrors that test every doctrine they know.',
    flavor: '"Faith is a shield, but the night grows darker." Your conviction provides comfort to others, even as the truth corrodes your own certainties.',
    bonusSkills: ['Accounting', 'History', 'Insight', 'Library Use', 'Occult', 'Persuade', 'Psychology', 'Foreign Language'],
    bonusAmount: 20,
    optionalSkills: ['Art', 'Bureaucracy', 'Charm', 'Medicine'],
    optionalCount: 2,
    bonds: 4,
    resources: 2,
  },
  {
    id: 'criminal',
    name: 'Criminal',
    ages: ['jazz', 'modern'],
    description: 'Those who operate outside the law—thieves, grifters, or enforcers who have learned that the underworld harbors more than just human predators.',
    flavor: '"Everyone has a price, and everyone has a secret." Some secrets, you have learned, cannot be traded away without a terrible cost.',
    bonusSkills: ['Alertness', 'Charm', 'Disguise', 'Drive', 'Firearms', 'Persuade', 'Stealth', 'Unarmed Combat'],
    bonusAmount: 20,
    optionalSkills: ['Demolitions', 'Insight', 'Intimidate', 'Melee Weapons'],
    optionalCount: 2,
    bonds: 3,
    resources: 1,
  },
  {
    id: 'dilettante',
    name: 'Dilettante',
    ages: ['jazz'],
    description: 'Wealthy socialites of independent means who pursue exotic hobbies and have the funds to indulge every dangerous curiosity.',
    flavor: '"Adventure is merely discomfort viewed in retrospect." Your money has opened every door—including those that should remain firmly shut.',
    bonusSkills: ['Accounting', 'Art', 'Charm', 'Firearms', 'History', 'Insight', 'Persuade', 'Ride'],
    bonusAmount: 20,
    optionalSkills: ['Foreign Language', 'Occult', 'Pilot', 'Swim'],
    optionalCount: 2,
    bonds: 3,
    resources: 4,
  },
  {
    id: 'doctor',
    name: 'Doctor',
    ages: ['jazz'],
    description: 'Physicians who have witnessed the limits of human endurance and the strange ailments that afflict those who look too closely at the unknown.',
    flavor: '"The body fails long before the mind surrenders." Your medical training has prepared you for trauma—but not for what the darkness truly does to a person.',
    bonusSkills: ['Accounting', 'Alertness', 'First Aid', 'Insight', 'Medicine', 'Persuade', 'Psychoanalysis', 'Surgery'],
    bonusAmount: 20,
    optionalSkills: ['Foreign Language', 'Library Use', 'Occult', 'Psychology'],
    optionalCount: 2,
    bonds: 4,
    resources: 3,
  },
  {
    id: 'entertainer',
    name: 'Entertainer',
    ages: ['jazz'],
    description: 'Performers, musicians, actors, and showmen who have honed the art of reading an audience and bending reality to their narrative.',
    flavor: '"Every performance is a kind of lie, and every lie has a cost." Yours may be steeper than most.',
    bonusSkills: ['Art', 'Alertness', 'Charm', 'Disguise', 'Insight', 'Persuade', 'Psychology', 'Stealth'],
    bonusAmount: 20,
    optionalSkills: ['Athletics', 'Drive', 'Foreign Language', 'Unarmed Combat'],
    optionalCount: 2,
    bonds: 3,
    resources: 2,
  },
  {
    id: 'investigator',
    name: 'Investigator',
    ages: ['jazz'],
    description: 'Private detectives and inquiry agents who have made a career of uncovering the secrets that others pay dearly to keep hidden.',
    flavor: '"Every case begins with a lie." The lies you now uncover are older and stranger than you could have imagined.',
    bonusSkills: ['Alertness', 'Charm', 'Disguise', 'Drive', 'Insight', 'Law', 'Persuade', 'Search'],
    bonusAmount: 20,
    optionalSkills: ['Firearms', 'First Aid', 'Psychology', 'Unarmed Combat'],
    optionalCount: 2,
    bonds: 3,
    resources: 2,
  },
  {
    id: 'laborer',
    name: 'Laborer',
    ages: ['jazz'],
    description: 'Working men and women whose physical toil has made them tough, resourceful, and deeply familiar with the underbelly of the world.',
    flavor: '"Hard work teaches humility, and humility may yet save your life." The calluses on your hands are your credentials.',
    bonusSkills: ['Athletics', 'Alertness', 'Craft', 'Drive', 'Navigate', 'Stealth', 'Survival', 'Unarmed Combat'],
    bonusAmount: 20,
    optionalSkills: ['Firearms', 'Heavy Weapons', 'Melee Weapons', 'Swim'],
    optionalCount: 2,
    bonds: 3,
    resources: 1,
  },
  {
    id: 'military_officer',
    name: 'Military Officer',
    ages: ['jazz'],
    description: 'Veterans who commanded troops in the great wars and have returned bearing invisible scars alongside their medals.',
    flavor: '"Command is loneliness." You have given orders that sent men to their deaths; now you face enemies that no rank can impress.',
    bonusSkills: ['Accounting', 'Alertness', 'Firearms', 'History', 'Insight', 'Military Training', 'Navigate', 'Persuade'],
    bonusAmount: 20,
    optionalSkills: ['Heavy Weapons', 'Law', 'Melee Weapons', 'Pilot'],
    optionalCount: 2,
    bonds: 3,
    resources: 2,
  },
  {
    id: 'nurse',
    name: 'Nurse',
    ages: ['jazz'],
    description: 'Skilled healers who work at the front lines of human suffering, bringing care and compassion to the broken and the lost.',
    flavor: '"Healing is a calling, not a profession." The wounds you now treat are stranger than any textbook prepared you for.',
    bonusSkills: ['Alertness', 'First Aid', 'Insight', 'Medicine', 'Persuade', 'Psychology', 'Search', 'Stealth'],
    bonusAmount: 20,
    optionalSkills: ['Art', 'Charm', 'Psychoanalysis', 'Surgery'],
    optionalCount: 2,
    bonds: 3,
    resources: 2,
  },
  {
    id: 'occultist',
    name: 'Occultist',
    ages: ['jazz', 'modern'],
    description: 'Students of forbidden knowledge and esoteric traditions who have peered behind the veil and found it harder to look away each time.',
    flavor: '"The price of knowledge is sanity." You have paid installments for years, and the final bill is approaching.',
    bonusSkills: ['Alertness', 'History', 'Insight', 'Library Use', 'Occult', 'Persuade', 'Psychoanalysis', 'Search'],
    bonusAmount: 20,
    optionalSkills: ['Art', 'Foreign Language', 'Psychology', 'Stealth'],
    optionalCount: 2,
    bonds: 3,
    resources: 1,
  },
  {
    id: 'reporter',
    name: 'Reporter',
    ages: ['jazz'],
    description: 'Journalists and correspondents who follow the story wherever it leads, even into the darkest corners of human—and inhuman—society.',
    flavor: '"The public has a right to know." Some truths, you are learning, the public is mercifully incapable of comprehending.',
    bonusSkills: ['Alertness', 'Charm', 'Drive', 'Insight', 'Law', 'Persuade', 'Psychology', 'Search'],
    bonusAmount: 20,
    optionalSkills: ['Art', 'Disguise', 'History', 'Navigate'],
    optionalCount: 2,
    bonds: 3,
    resources: 2,
  },
  {
    id: 'soldier',
    name: 'Soldier',
    ages: ['jazz'],
    description: 'Combat veterans hardened by the horrors of war, now discovering that the battlefield was the least of humanity\'s nightmares.',
    flavor: '"Survival is not the same as living." You have survived things no human being should witness; now you add stranger things to that list.',
    bonusSkills: ['Alertness', 'Athletics', 'Firearms', 'First Aid', 'Navigate', 'Stealth', 'Survival', 'Unarmed Combat'],
    bonusAmount: 20,
    optionalSkills: ['Demolitions', 'Heavy Weapons', 'Melee Weapons', 'Military Training'],
    optionalCount: 2,
    bonds: 2,
    resources: 1,
  },
  {
    id: 'tradesperson',
    name: 'Tradesperson',
    ages: ['jazz'],
    description: 'Skilled craftspeople and tradespeople whose practical knowledge and community connections make them unexpectedly resilient investigators.',
    flavor: '"Know your tools, and know your limits." You know both better than most; the horrors that lurk ahead respect neither.',
    bonusSkills: ['Accounting', 'Alertness', 'Craft', 'Drive', 'First Aid', 'Navigate', 'Persuade', 'Search'],
    bonusAmount: 20,
    optionalSkills: ['Athletics', 'Heavy Weapons', 'Melee Weapons', 'Unarmed Combat'],
    optionalCount: 2,
    bonds: 3,
    resources: 2,
  },

  // ── Modern Age ────────────────────────────────────────────

  {
    id: 'federal_agent',
    name: 'Federal Agent',
    ages: ['modern'],
    description: 'Law enforcement officers backed by the full authority of the federal government, trained to investigate crimes that cross state lines—and now, stranger thresholds.',
    flavor: '"Procedure protects the innocent." The procedures in your manual, however, did not anticipate what you are about to encounter.',
    bonusSkills: ['Alertness', 'Drive', 'Firearms', 'Insight', 'Law', 'Persuade', 'Psychology', 'Search'],
    bonusAmount: 20,
    optionalSkills: ['Computer Science', 'Forensics', 'SIGINT', 'Unarmed Combat'],
    optionalCount: 2,
    bonds: 3,
    resources: 2,
  },
  {
    id: 'first_responder',
    name: 'First Responder',
    ages: ['modern'],
    description: 'Paramedics, firefighters, and emergency personnel who race toward catastrophe while others flee—now responding to catastrophes that defy all training.',
    flavor: '"We run toward the fire." Some fires, you are discovering, were never meant to be extinguished.',
    bonusSkills: ['Alertness', 'Athletics', 'Drive', 'First Aid', 'Insight', 'Medicine', 'Navigate', 'Search'],
    bonusAmount: 20,
    optionalSkills: ['Computer Science', 'Heavy Machinery', 'Persuade', 'Psychology'],
    optionalCount: 2,
    bonds: 3,
    resources: 2,
  },
  {
    id: 'journalist',
    name: 'Journalist',
    ages: ['modern'],
    description: 'Investigative reporters and media professionals who dig for buried truths in a world drowning in misinformation.',
    flavor: '"Follow the evidence." The evidence you are now following points somewhere beyond the edge of the map.',
    bonusSkills: ['Alertness', 'Charm', 'Drive', 'Insight', 'Law', 'Persuade', 'Psychology', 'Search'],
    bonusAmount: 20,
    optionalSkills: ['Art', 'Computer Science', 'Disguise', 'SIGINT'],
    optionalCount: 2,
    bonds: 3,
    resources: 2,
  },
  {
    id: 'medical_professional',
    name: 'Medical Professional',
    ages: ['modern'],
    description: 'Physicians, surgeons, and specialists who confront the fragility of the human body every day—and have now begun to suspect something worse lurks beneath.',
    flavor: '"First, do no harm." The entity you just encountered does not share your ethical framework.',
    bonusSkills: ['Alertness', 'First Aid', 'Insight', 'Medicine', 'Persuade', 'Psychoanalysis', 'Psychology', 'Surgery'],
    bonusAmount: 20,
    optionalSkills: ['Computer Science', 'Forensics', 'Law', 'Search'],
    optionalCount: 2,
    bonds: 4,
    resources: 3,
  },
  {
    id: 'military_operator',
    name: 'Military Operator',
    ages: ['modern'],
    description: 'Special operations soldiers and elite warriors whose advanced training is about to meet its most severe test.',
    flavor: '"Violence is a tool, not an answer." The tools you carry were forged for human conflicts. What waits ahead is not human.',
    bonusSkills: ['Alertness', 'Athletics', 'Drive', 'Firearms', 'First Aid', 'Navigate', 'Stealth', 'Unarmed Combat'],
    bonusAmount: 20,
    optionalSkills: ['Demolitions', 'Heavy Weapons', 'Military Training', 'SIGINT'],
    optionalCount: 2,
    bonds: 2,
    resources: 2,
  },
  {
    id: 'scientist',
    name: 'Scientist',
    ages: ['modern'],
    description: 'Researchers and scientists whose commitment to empirical inquiry is being stress-tested by phenomena that violate every known law of nature.',
    flavor: '"Data does not lie." But data can be misinterpreted, and what your instruments are reading cannot possibly be correct.',
    bonusSkills: ['Accounting', 'Alertness', 'Computer Science', 'Forensics', 'History', 'Insight', 'Occult', 'Search'],
    bonusAmount: 20,
    optionalSkills: ['Foreign Language', 'Library Use', 'Medicine', 'Psychology'],
    optionalCount: 2,
    bonds: 4,
    resources: 2,
  },
  {
    id: 'security_specialist',
    name: 'Security Specialist',
    ages: ['modern'],
    description: 'Corporate security operatives, private investigators, and protection specialists who navigate the shadowy margins between law and necessity.',
    flavor: '"Trust no one, verify everything." A philosophy about to be tested by things that exist in no database.',
    bonusSkills: ['Alertness', 'Athletics', 'Drive', 'Firearms', 'Insight', 'Law', 'Search', 'Unarmed Combat'],
    bonusAmount: 20,
    optionalSkills: ['Computer Science', 'Disguise', 'SIGINT', 'Stealth'],
    optionalCount: 2,
    bonds: 3,
    resources: 2,
  },
  {
    id: 'tech_specialist',
    name: 'Tech Specialist',
    ages: ['modern'],
    description: 'Hackers, engineers, and digital investigators whose mastery of technology is their greatest weapon—and greatest vulnerability.',
    flavor: '"There are no secrets on the internet." What you have found hidden in encrypted servers was meant to stay buried forever.',
    bonusSkills: ['Alertness', 'Computer Science', 'Craft', 'Electronics', 'Insight', 'Search', 'SIGINT', 'Stealth'],
    bonusAmount: 20,
    optionalSkills: ['Demolitions', 'Forensics', 'Heavy Machinery', 'Law'],
    optionalCount: 2,
    bonds: 3,
    resources: 2,
  },
];

// ── Gritty Edges ─────────────────────────────────────────────

const GRITTY_EDGES = [
  {
    id: 'hardened',
    name: 'Hardened',
    cost: 3,
    description: 'You have faced the abyss and returned scarred but functional. Your Breaking Point increases by 5.',
  },
  {
    id: 'quick_healer',
    name: 'Quick Healer',
    cost: 2,
    description: 'Your body knits itself with remarkable speed. You heal 2 HP per day of rest instead of 1.',
  },
  {
    id: 'iron_will',
    name: 'Iron Will',
    cost: 3,
    description: 'A bedrock of psychological resilience keeps you upright when others crumble. Add +5 to all Sanity checks.',
  },
  {
    id: 'combat_veteran',
    name: 'Combat Veteran',
    cost: 2,
    description: 'Instinct honed by violence gives you an edge. Gain +10% to Unarmed Combat and one weapon skill of your choice.',
  },
  {
    id: 'contacts',
    name: 'Well-Connected',
    cost: 2,
    description: 'Your network of allies runs deeper than most. Gain one additional Bond beyond your archetype total.',
  },
  {
    id: 'resourceful',
    name: 'Resourceful',
    cost: 2,
    description: 'You have cultivated reserves of wealth, influence, or supplies. Your Resources rating increases by 1.',
  },
];

// ── Step config ───────────────────────────────────────────────

const STEPS = [
  { id: 1, label: 'Era',        title: 'Choose Your Era' },
  { id: 2, label: 'Tone',       title: 'Set the Tone' },
  { id: 3, label: 'Attributes', title: 'Roll Your Attributes' },
  { id: 4, label: 'Archetype',  title: 'Choose Your Archetype' },
  { id: 5, label: 'Points',     title: 'Distribute Your Points' },
  { id: 6, label: 'Identity',   title: 'Forge Your Identity' },
];
