/* ============================================================
   CTHULHU ETERNAL — DATA
   Skills, Archetypes, Edges
   ============================================================ */

const ATTRIBUTES = ['STR', 'CON', 'DEX', 'INT', 'POW', 'CHA'];
const ATTRIBUTE_FULL = {
  STR: 'Strength',
  CON: 'Constitution',
  DEX: 'Dexterity',
  INT: 'Intelligence',
  POW: 'Power',
  CHA: 'Charisma',
};

// ── Base Skill Lists ─────────────────────────────────────────

const JAZZ_SKILLS = {
  'Administration':           10,
  'Alertness':                20,
  'Anthropology':              0,
  'Appraise':                 10,
  'Archeology':                0,
  'Art (Type)':                0,
  'Athletics':                30,
  'Charm':                    20,
  'Craft (Type)':              0,
  'Disguise':                 10,
  'Dodge':                    30,
  'Drive':                    20,
  'Firearms':                 20,
  'First Aid':                10,
  'Foreign Language (Type)':   0,
  'Harangue':                 10,
  'Heavy Machinery':          10,
  'History':                  10,
  'Insight':                  10,
  'Law (Type)':                0,
  'Medicine':                  0,
  'Melee Weapons':            30,
  'Military Training (Type)':  0,
  'Natural World':            10,
  'Navigate':                 10,
  'Occult':                   10,
  'Persuade':                 20,
  'Pilot (Type)':              0,
  'Psychoanalyze':            10,
  'Regional Lore (Type)':      0,
  'Research':                 10,
  'Ride':                     10,
  'Science (Type)':            0,
  'Search':                   20,
  'Social Etiquette':         10,
  'Stealth':                  10,
  'Streetwise (Type)':         0,
  'Surgery':                   0,
  'Survival (Type)':          10,
  'Swim':                     20,
  'Track':                    10,
  'Unarmed Combat':           20,
  'Unnatural':                 0,
  'Use Gadgets':               0,
};

const MODERN_SKILLS = {
  'Administration':           10,
  'Alertness':                20,
  'Anthropology':              0,
  'Appraise':                 10,
  'Archeology':                0,
  'Art (Type)':                0,
  'Athletics':                30,
  'Charm':                    20,
  'Craft (Type)':              0,
  'Disguise':                 10,
  'Dodge':                    30,
  'Drive':                    20,
  'Firearms':                 20,
  'First Aid':                10,
  'Foreign Language (Type)':   0,
  'Forensics':                 0,
  'Harangue':                 10,
  'Heavy Machinery':          10,
  'History':                  10,
  'Insight':                  10,
  'Law (Type)':                0,
  'Medicine':                  0,
  'Melee Weapons':            30,
  'Military Training (Type)':  0,
  'Natural World':            10,
  'Navigate':                 10,
  'Occult':                   10,
  'Persuade':                 20,
  'Pharmacy':                  0,
  'Pilot (Type)':              0,
  'Psychoanalyze':            10,
  'Regional Lore (Type)':      0,
  'Research':                 10,
  'Ride':                     10,
  'Science (Type)':            0,
  'Search':                   20,
  'Stealth':                  10,
  'Surgery':                   0,
  'Survival (Type)':          10,
  'Swim':                     20,
  'Technology Use':            0,
  'Track':                    10,
  'Unarmed Combat':           20,
  'Unnatural':                 0,
};

// ── Skill Descriptions ──────────────────────────────────────
// Shared descriptions (Jazz Age & Modern Age). Keys match the skill names in
// JAZZ_SKILLS / MODERN_SKILLS exactly (including "(Type)" placeholders).

const SKILL_DESCRIPTIONS = {
  'Administration':           'Manage bureaucratic systems, navigate red tape, understand organizational structures, and handle paperwork. Useful for accessing official records or running an organization.',
  'Alertness':                'Notice things happening around you — sounds, smells, movement, and other environmental cues — without actively searching. Your passive awareness of your surroundings.',
  'Anthropology':             'Study human cultures, customs, and social structures across time and geography. Helps interpret rituals, taboos, and cultural artifacts.',
  'Appraise':                 'Estimate the value, authenticity, and quality of objects such as antiques, art, jewelry, or contraband. Also useful for spotting forgeries.',
  'Archeology':               'Excavate, analyze, and interpret physical remains of past cultures. Identify artifacts, date ruins, and understand ancient sites.',
  'Art (Type)':               'Create, perform, or critically evaluate a specific art form (e.g., Painting, Music, Writing). Higher skill means finer technique and deeper appreciation.',
  'Athletics':                'Perform feats of physical exertion — running, jumping, climbing, and throwing. Your general physical coordination and fitness.',
  'Charm':                    'Win people over through warmth, wit, flattery, or personal magnetism. Use to make a good first impression, seduce, or put someone at ease.',
  'Craft (Type)':             'Build, repair, or create physical objects using a specific trade skill (e.g., Carpentry, Mechanics, Electronics). Reflects hands-on technical knowledge.',
  'Disguise':                 'Alter your appearance — clothing, makeup, mannerisms — to pass as someone else or avoid recognition.',
  'Dodge':                    'React quickly to avoid physical harm — ducking, weaving, rolling out of the way of attacks or environmental hazards.',
  'Drive':                    'Operate wheeled vehicles under normal or difficult conditions. High skill covers high-speed pursuits, off-road driving, and vehicle control in emergencies.',
  'Firearms':                 'Aim and fire ranged weapons including handguns, rifles, and shotguns. Covers both shooting accuracy and safe weapon handling.',
  'First Aid':                'Treat injuries in the field: stop bleeding, stabilize the wounded, and prevent death in the short term. Does not replace Medicine for complex treatment.',
  'Foreign Language (Type)':  'Read, write, and speak a language other than your native tongue (e.g., French, Mandarin, Arabic). Skill level reflects fluency.',
  'Forensics':                'Examine crime scenes and physical evidence to reconstruct events. Includes analyzing wounds, collecting trace evidence, and reading autopsy reports.',
  'Harangue':                 'Persuade or intimidate a group through forceful public speaking — rallying a crowd, delivering a rousing speech, or browbeating an audience.',
  'Heavy Machinery':          'Operate and maintain large industrial or construction equipment such as cranes, bulldozers, and forklifts.',
  'History':                  'Recall or research events of the past — dates, figures, causes, and cultural context. Also helps interpret historical documents and artifacts.',
  'Insight':                  'Read people: detect lies, sense emotional states, and intuit hidden motives. Your ability to understand what others are really thinking.',
  'Law (Type)':               'Understand the legal system in a specific jurisdiction (e.g., US Federal, English Common Law). Navigate legal proceedings, draft documents, and spot illegal activity.',
  'Medicine':                 'Diagnose and treat illness, injury, and disease with professional medical knowledge. Covers surgical preparation, prescribing treatment, and long-term care.',
  'Melee Weapons':            'Fight effectively with hand-held weapons — knives, clubs, swords, and improvised tools — in close combat.',
  'Military Training (Type)': 'Apply specialist knowledge from military service — tactics, weapons drills, fieldcraft, and unit discipline. Specify a branch or specialization (e.g., Infantry, Artillery).',
  'Natural World':            'Identify plants, animals, and natural phenomena; understand ecosystems and wilderness environments. Useful for survival, tracking, and interpreting nature.',
  'Navigate':                 'Find your way using maps, compasses, stars, or landmarks. Covers route planning and orientation in both urban and wilderness settings.',
  'Occult':                   'Know the history, symbolism, and lore of the occult — magic traditions, secret societies, and esoteric texts. Does not grant actual supernatural power.',
  'Persuade':                 'Convince someone through reasoned argument, logical appeal, or well-placed negotiation. Less forceful than Harangue; more reasoned than Charm.',
  'Pharmacy':                 'Compound, identify, and safely dispense drugs and pharmaceuticals. Includes recognizing toxic substances and understanding drug interactions.',
  'Pilot (Type)':             'Fly or navigate a specific type of vessel or aircraft (e.g., Propeller Plane, Motorboat, Sailing Vessel) under normal or emergency conditions.',
  'Psychoanalyze':            'Apply psychoanalytic technique to help others process trauma and mental illness. Also useful for understanding psychological disorders and motivations.',
  'Regional Lore (Type)':     'Deep knowledge of a specific region — its geography, history, factions, notable figures, and hidden secrets (e.g., New England, Arkham, the Congo).',
  'Research':                 'Find information through libraries, archives, and reference sources. Covers literature searches, following citation trails, and working with historical records.',
  'Ride':                     'Control and care for riding animals — primarily horses — including mounting, steering, and managing difficult terrain or startled mounts.',
  'Science (Type)':           'Apply rigorous scientific methodology and specialized knowledge in a discipline (e.g., Biology, Chemistry, Physics, Astronomy) to analyze phenomena and draw conclusions.',
  'Search':                   'Actively look for hidden or concealed things — secret doors, hidden objects, subtle clues at a crime scene — through careful examination.',
  'Social Etiquette':         'Navigate formal and high-society social situations with grace: correct forms of address, appropriate behavior, and unspoken rules of polite company.',
  'Stealth':                  'Move quietly, stay hidden, and avoid detection. Covers sneaking, shadowing a target, and remaining unseen in a crowd or at night.',
  'Streetwise (Type)':        'Navigate the criminal underworld or street-level culture of a specific city or region — where to buy contraband, who the players are, and how to avoid trouble.',
  'Surgery':                  'Perform invasive medical procedures to repair internal injuries, remove foreign objects, or treat conditions requiring an operation. Requires tools and a sterile environment.',
  'Survival (Type)':          'Endure and navigate hostile environments of a specific type (e.g., Arctic, Desert, Jungle) — finding food and water, building shelter, and avoiding natural hazards.',
  'Swim':                     'Move through water and stay afloat in difficult conditions such as rough seas, strong currents, or while encumbered.',
  'Technology Use':           'Operate, troubleshoot, and make effective use of modern technology — computers, communications equipment, and electronic devices.',
  'Track':                    'Follow the physical traces left by people or animals — footprints, disturbed vegetation, scent trails — across varied terrain.',
  'Unarmed Combat':           'Fight effectively with fists, feet, grappling, or improvised holds. Covers boxing, wrestling, and brawling in close quarters.',
  'Unnatural':                'Awareness of and exposure to forces beyond human understanding. This skill cannot be improved voluntarily — it only rises through encounters with the Unnatural.',
  'Use Gadgets':              'Operate unfamiliar mechanical or electrical devices, improvise tools from available components, and jury-rig solutions in the field.',
};

// ── Archetypes ───────────────────────────────────────────────

const ARCHETYPES = [

  // ── Jazz Age ──────────────────────────────────────────────

  {
    id: 'alienist',
    name: 'Alienist / Psychiatrist',
    ages: ['jazz'],
    recommendedStats: ['POW', 'INT'],
    description: 'Psychiatrists who probe the fragile boundaries of the human mind.',
    archetypeSkills: [
      { name: 'Anthropology',        value: 50 },
      { name: 'Insight',             value: 60 },
      { name: 'Medicine',            value: 40 },
      { name: 'Psychoanalyze',       value: 70 },
      { name: 'Science (Type)',      value: 50 },
      { name: 'Social Etiquette',    value: 40 },
    ],
    optionalSkills: [
      { name: 'Administration',          value: 50 },
      { name: 'Alertness',               value: 60 },
      { name: 'Charm',                   value: 60 },
      { name: 'Foreign Language (Type)', value: 40 },
      { name: 'Law (Type)',              value: 40 },
      { name: 'Research',                value: 50 },
    ],
    optionalCount: 3,
    resources: 5,
    bonds: 3,
  },
  {
    id: 'antiquarian',
    name: 'Antiquarian / Book Dealer',
    ages: ['jazz'],
    recommendedStats: ['INT', 'CHA'],
    description: 'Collectors and dealers of rare books, curiosities, and forgotten lore.',
    archetypeSkills: [
      { name: 'Administration', value: 50 },
      { name: 'Appraise',       value: 60 },
      { name: 'History',        value: 80 },
      { name: 'Research',       value: 60 },
      { name: 'Persuade',       value: 60 },
      { name: 'Search',         value: 60 },
    ],
    optionalSkills: [
      { name: 'Charm',                   value: 60 },
      { name: 'Craft (Type)',            value: 40 },
      { name: 'Foreign Language (Type)', value: 40 },
      { name: 'Occult',                  value: 50 },
      { name: 'Regional Lore (Type)',    value: 40 },
      { name: 'Streetwise (Type)',       value: 40 },
      { name: 'Use Gadgets',             value: 40 },
    ],
    optionalCount: 4,
    resources: 4,
    bonds: 3,
  },
  {
    id: 'artist',
    name: 'Artist / Craftsperson',
    ages: ['jazz'],
    recommendedStats: ['DEX'],
    description: 'Creative souls whose work brings them dangerously close to the unknown.',
    archetypeSkills: [
      { name: 'Appraise',          value: 40 },
      { name: 'Art (Type)',        value: 60 }, // primary art specialization
      { name: 'Art (Type)',        value: 40 }, // secondary art specialization
      { name: 'Insight',           value: 60 },
      { name: 'Search',            value: 60 },
      { name: 'Streetwise (Type)', value: 30 },
      { name: 'Social Etiquette',  value: 50 },
    ],
    optionalSkills: [
      { name: 'Administration',  value: 50 },
      { name: 'Alertness',       value: 60 },
      { name: 'Anthropology',    value: 40 },
      { name: 'Athletics',       value: 70 },
      { name: 'Harangue',        value: 50 },
      { name: 'Heavy Machinery', value: 50 },
      { name: 'Natural World',   value: 50 },
      { name: 'Use Gadgets',     value: 40 },
    ],
    optionalCount: 4,
    resources: 4,
    bonds: 3,
  },
  {
    id: 'bon_vivant',
    name: 'Bon Vivant / Occult Dabbler',
    ages: ['jazz'],
    recommendedStats: ['POW', 'CHA'],
    description: 'Wealthy pleasure-seekers drawn irresistibly toward occult mysteries.',
    archetypeSkills: [
      { name: 'Anthropology',   value: 30 },
      { name: 'Insight',        value: 50 },
      { name: 'Occult',         value: 70 },
      { name: 'Persuade',       value: 40 },
      { name: 'Research',       value: 40 },
      { name: 'Social Etiquette', value: 60 },
    ],
    optionalSkills: [
      { name: 'Art (Type)',              value: 40 },
      { name: 'Charm',                   value: 60 },
      { name: 'Foreign Language (Type)', value: 40 },
      { name: 'History',                 value: 50 },
      { name: 'Psychoanalyze',           value: 50 },
      { name: 'Regional Lore (Type)',    value: 40 },
    ],
    optionalCount: 3,
    resources: 5,
    bonds: 4,
  },
  {
    id: 'criminal',
    name: 'Criminal / Gangster',
    ages: ['jazz'],
    recommendedStats: ['STR', 'DEX'],
    description: 'Operators in the underworld who have encountered horrors beyond human crime.',
    archetypeSkills: [
      { name: 'Alertness',         value: 50 },
      { name: 'Appraise',          value: 40 },
      { name: 'Athletics',         value: 50 },
      { name: 'Insight',           value: 40 },
      { name: 'Search',            value: 50 },
      { name: 'Stealth',           value: 60 },
      { name: 'Streetwise (Type)', value: 40 },
    ],
    optionalSkills: [
      { name: 'Craft (Type)',  value: 40 },
      { name: 'Disguise',      value: 50 },
      { name: 'Firearms',      value: 60 },
      { name: 'Harangue',      value: 50 },
      { name: 'Law (Type)',    value: 40 },
      { name: 'Melee Weapons', value: 70 },
      { name: 'Unarmed Combat', value: 60 },
      { name: 'Use Gadgets',   value: 40 },
    ],
    optionalCount: 3,
    resources: 5,
    bonds: 4,
  },
  {
    id: 'doctor',
    name: 'Doctor / Nurse',
    ages: ['jazz'],
    recommendedStats: ['INT'],
    description: 'Medical professionals confronting ailments no textbook ever prepared them for.',
    archetypeSkills: [
      { name: 'Administration',  value: 30 },
      { name: 'Charm',           value: 60 },
      { name: 'First Aid',       value: 50 },
      { name: 'Insight',         value: 50 },
      { name: 'Medicine',        value: 50 },
      { name: 'Search',          value: 60 },
      { name: 'Social Etiquette', value: 50 },
      { name: 'Surgery',         value: 50 },
    ],
    optionalSkills: [
      { name: 'Foreign Language (Type)', value: 40 },
      { name: 'Military Training (Type)', value: 40 },
      { name: 'Psychoanalyze',           value: 50 },
      { name: 'Research',                value: 50 },
      { name: 'Science (Type)',          value: 40 },
      { name: 'Use Gadgets',             value: 40 },
    ],
    optionalCount: 2,
    resources: 5,
    bonds: 3,
  },
  {
    id: 'historian',
    name: 'Historian / Genealogist',
    ages: ['jazz'],
    recommendedStats: ['INT', 'CHA'],
    description: 'Scholars of the past who discover that some history was never meant to be found.',
    archetypeSkills: [
      { name: 'Administration',  value: 60 },
      { name: 'Anthropology',    value: 50 },
      { name: 'Archeology',      value: 50 },
      { name: 'History',         value: 70 },
      { name: 'Research',        value: 60 },
      { name: 'Social Etiquette', value: 40 },
    ],
    optionalSkills: [
      { name: 'Art (Type)',              value: 40 },
      { name: 'Craft (Type)',            value: 40 },
      { name: 'Foreign Language (Type)', value: 40 },
      { name: 'Law (Type)',              value: 40 },
      { name: 'Military Training (Type)', value: 40 },
      { name: 'Persuade',               value: 60 },
      { name: 'Regional Lore (Type)',   value: 40 },
      { name: 'Search',                 value: 60 },
    ],
    optionalCount: 4,
    resources: 4,
    bonds: 3,
  },
  {
    id: 'journalist',
    name: 'Journalist / Author',
    ages: ['jazz'],
    recommendedStats: ['INT', 'CHA'],
    description: 'Reporters who chase stories into the darkest corners of the world.',
    archetypeSkills: [
      { name: 'Alertness',       value: 50 },
      { name: 'Art (Type)',      value: 50 },
      { name: 'Insight',         value: 60 },
      { name: 'Research',        value: 60 },
      { name: 'Search',          value: 60 },
      { name: 'Social Etiquette', value: 30 },
    ],
    optionalSkills: [
      { name: 'Administration',          value: 50 },
      { name: 'Anthropology',            value: 40 },
      { name: 'Archeology',              value: 40 },
      { name: 'Foreign Language (Type)', value: 40 },
      { name: 'History',                 value: 50 },
      { name: 'Law (Type)',              value: 40 },
      { name: 'Occult',                  value: 50 },
      { name: 'Regional Lore (Type)',    value: 40 },
      { name: 'Science (Type)',          value: 40 },
      { name: 'Use Gadgets',             value: 40 },
    ],
    optionalCount: 4,
    resources: 4,
    bonds: 4,
  },
  {
    id: 'private_eye',
    name: 'Private Eye / Detective',
    ages: ['jazz'],
    recommendedStats: ['INT', 'STR'],
    description: 'Detectives who uncover secrets that sometimes cannot be safely known.',
    archetypeSkills: [
      { name: 'Alertness',         value: 50 },
      { name: 'Firearms',          value: 60 },
      { name: 'First Aid',         value: 50 },
      { name: 'Insight',           value: 50 },
      { name: 'Law (Type)',        value: 50 },
      { name: 'Streetwise (Type)', value: 40 },
      { name: 'Search',            value: 70 },
      { name: 'Use Gadgets',       value: 40 },
    ],
    optionalSkills: [
      { name: 'Administration',  value: 50 },
      { name: 'Social Etiquette', value: 50 },
      { name: 'Athletics',       value: 70 },
      { name: 'Charm',           value: 60 },
      { name: 'Disguise',        value: 50 },
      { name: 'Dodge',           value: 70 },
      { name: 'Drive',           value: 60 },
      { name: 'Harangue',        value: 50 },
      { name: 'Melee Weapons',   value: 70 },
      { name: 'Research',        value: 50 },
    ],
    optionalCount: 3,
    resources: 4,
    bonds: 3,
  },
  {
    id: 'professor',
    name: 'Professor / Librarian',
    ages: ['jazz'],
    recommendedStats: ['INT', 'POW'],
    description: 'Academics whose years of study have not prepared them for the real truth.',
    archetypeSkills: [
      { name: 'Administration',  value: 40 },
      { name: 'Insight',         value: 60 },
      { name: 'Persuade',        value: 60 },
      { name: 'Research',        value: 70 },
      { name: 'Search',          value: 60 },
      { name: 'Social Etiquette', value: 50 },
      { name: 'Use Gadgets',     value: 40 },
    ],
    optionalSkills: [
      { name: 'Anthropology',            value: 40 },
      { name: 'Archeology',              value: 40 },
      { name: 'Art (Type)',              value: 40 },
      { name: 'Foreign Language (Type)', value: 40 },
      { name: 'History',                 value: 50 },
      { name: 'Law (Type)',              value: 40 },
      { name: 'Medicine',                value: 40 },
      { name: 'Occult',                  value: 50 },
      { name: 'Regional Lore (Type)',    value: 40 },
      { name: 'Science (Type)',          value: 40 },
    ],
    optionalCount: 5,
    resources: 4,
    bonds: 2,
  },
  {
    id: 'scientist',
    name: 'Scientist / Inventor',
    ages: ['jazz'],
    recommendedStats: ['INT', 'DEX'],
    description: 'Investigators whose empirical method meets phenomena that defy all known laws.',
    archetypeSkills: [
      { name: 'Craft (Type)',      value: 50 },
      { name: 'Law (Type)',        value: 20 },
      { name: 'Research',          value: 60 },
      { name: 'Science (Type)',    value: 60 },
      { name: 'Search',            value: 60 },
      { name: 'Social Etiquette',  value: 30 },
      { name: 'Use Gadgets',       value: 50 },
    ],
    optionalSkills: [
      { name: 'Anthropology',             value: 40 },
      { name: 'Archeology',               value: 40 },
      { name: 'Firearms',                 value: 60 },
      { name: 'Foreign Language (Type)',  value: 40 },
      { name: 'Heavy Machinery',          value: 50 },
      { name: 'Military Training (Type)', value: 40 },
      { name: 'Psychoanalyze',            value: 50 },
      { name: 'Science (Type)',           value: 40 },
    ],
    optionalCount: 4,
    resources: 5,
    bonds: 2,
  },

  // ── Modern Age ────────────────────────────────────────────

  {
    id: 'artist_modern',
    name: 'Artist / Craftsperson',
    ages: ['modern'],
    recommendedStats: ['DEX'],
    description: 'Creative professionals whose work occasionally glimpses what lies beyond.',
    archetypeSkills: [
      { name: 'Appraise',        value: 40 },
      { name: 'Art (Type)',      value: 60 },
      { name: 'Craft (Type)',    value: 40 },
      { name: 'Charm',           value: 60 },
      { name: 'Insight',         value: 60 },
      { name: 'Persuade',        value: 60 },
      { name: 'Search',          value: 60 },
    ],
    optionalSkills: [
      { name: 'Administration',       value: 50 },
      { name: 'Alertness',            value: 60 },
      { name: 'Anthropology',         value: 40 },
      { name: 'Athletics',            value: 70 },
      { name: 'Craft (Type)',         value: 40 },
      { name: 'Harangue',             value: 50 },
      { name: 'Heavy Machinery',      value: 50 },
      { name: 'Regional Lore (Type)', value: 40 },
      { name: 'Technology Use',       value: 40 },
    ],
    optionalCount: 5,
    resources: 3,
    bonds: 3,
  },
  {
    id: 'author',
    name: 'Author / Blogger',
    ages: ['modern'],
    recommendedStats: ['INT', 'CHA'],
    description: 'Writers and bloggers who stumble onto stories the world was better not knowing.',
    archetypeSkills: [
      { name: 'Alertness',      value: 50 },
      { name: 'Art (Type)',     value: 50 },
      { name: 'Insight',        value: 60 },
      { name: 'Research',       value: 60 },
      { name: 'Search',         value: 60 },
      { name: 'Technology Use', value: 20 },
    ],
    optionalSkills: [
      { name: 'Anthropology',            value: 40 },
      { name: 'Archeology',              value: 40 },
      { name: 'Foreign Language (Type)', value: 40 },
      { name: 'Harangue',                value: 50 },
      { name: 'History',                 value: 50 },
      { name: 'Law (Type)',              value: 40 },
      { name: 'Occult',                  value: 50 },
      { name: 'Regional Lore (Type)',    value: 40 },
      { name: 'Science (Type)',          value: 40 },
    ],
    optionalCount: 4,
    resources: 4,
    bonds: 4,
  },
  {
    id: 'conspiracy_theorist',
    name: 'Conspiracy Theorist / Expert',
    ages: ['modern'],
    recommendedStats: ['CHA', 'POW'],
    description: 'Researchers convinced that the truth is out there—and horrified to find it.',
    archetypeSkills: [
      { name: 'Craft (Type)',    value: 40 },
      { name: 'Firearms',        value: 50 },
      { name: 'First Aid',       value: 40 },
      { name: 'Natural World',   value: 50 },
      { name: 'Navigate',        value: 50 },
      { name: 'Search',          value: 50 },
      { name: 'Survival (Type)', value: 50 },
      { name: 'Track',           value: 50 },
    ],
    optionalSkills: [
      { name: 'Firearms',        value: 60 },
      { name: 'Heavy Machinery', value: 50 },
      { name: 'History',         value: 50 },
      { name: 'Melee Weapons',   value: 70 },
      { name: 'Occult',          value: 50 },
      { name: 'Pilot (Type)',    value: 40 },
      { name: 'Ride',            value: 50 },
      { name: 'Survival (Type)', value: 50 },
      { name: 'Unarmed Combat',  value: 60 },
    ],
    optionalCount: 4,
    resources: 3,
    bonds: 4,
  },
  {
    id: 'criminal_modern',
    name: 'Criminal',
    ages: ['modern'],
    recommendedStats: ['DEX'],
    description: 'Operators outside the law who encounter something worse than human predators.',
    archetypeSkills: [
      { name: 'Alertness',   value: 40 },
      { name: 'Appraise',    value: 40 },
      { name: 'Craft (Type)', value: 40 },
      { name: 'Harangue',    value: 40 },
      { name: 'Law (Type)',  value: 30 },
      { name: 'Stealth',     value: 60 },
      { name: 'Search',      value: 50 },
    ],
    optionalSkills: [
      { name: 'Administration',  value: 50 },
      { name: 'Art (Type)',      value: 40 },
      { name: 'Athletics',       value: 70 },
      { name: 'Charm',           value: 60 },
      { name: 'Dodge',           value: 70 },
      { name: 'Firearms',        value: 60 },
      { name: 'Insight',         value: 50 },
      { name: 'Melee Weapons',   value: 70 },
      { name: 'Technology Use',  value: 40 },
    ],
    optionalCount: 3,
    resources: 5,
    bonds: 4,
  },
  {
    id: 'doctor_modern',
    name: 'Doctor / Nurse',
    ages: ['modern'],
    recommendedStats: ['INT'],
    description: 'Medical professionals facing ailments that no clinical training anticipated.',
    archetypeSkills: [
      { name: 'Administration',  value: 30 },
      { name: 'Charm',           value: 40 },
      { name: 'First Aid',       value: 50 },
      { name: 'Insight',         value: 50 },
      { name: 'Medicine',        value: 50 },
      { name: 'Science (Type)',  value: 40 },
      { name: 'Search',          value: 60 },
      { name: 'Surgery',         value: 40 },
      { name: 'Technology Use',  value: 30 },
    ],
    optionalSkills: [
      { name: 'Foreign Language (Type)',  value: 40 },
      { name: 'Military Training (Type)', value: 40 },
      { name: 'Forensics',                value: 40 },
      { name: 'Pharmacy',                 value: 40 },
      { name: 'Psychoanalyze',            value: 50 },
      { name: 'Research',                 value: 50 },
      { name: 'Science (Type)',           value: 40 },
    ],
    optionalCount: 2,
    resources: 5,
    bonds: 3,
  },
  {
    id: 'historian_modern',
    name: 'Historian / Genealogist',
    ages: ['modern'],
    recommendedStats: ['INT', 'CHA'],
    description: 'Scholars of history who find certain records were buried for good reason.',
    archetypeSkills: [
      { name: 'Administration',  value: 50 },
      { name: 'Anthropology',    value: 50 },
      { name: 'Archeology',      value: 50 },
      { name: 'History',         value: 70 },
      { name: 'Research',        value: 60 },
      { name: 'Technology Use',  value: 30 },
    ],
    optionalSkills: [
      { name: 'Art (Type)',              value: 40 },
      { name: 'Craft (Type)',            value: 40 },
      { name: 'Foreign Language (Type)', value: 40 },
      { name: 'Law (Type)',              value: 40 },
      { name: 'Military Training (Type)', value: 40 },
      { name: 'Persuade',               value: 60 },
      { name: 'Regional Lore (Type)',   value: 40 },
      { name: 'Search',                 value: 60 },
    ],
    optionalCount: 3,
    resources: 4,
    bonds: 4,
  },
  {
    id: 'law_enforcer',
    name: 'Law Enforcer / Agent',
    ages: ['modern'],
    recommendedStats: ['CON', 'CHA'],
    description: 'Law enforcement officers whose jurisdiction now extends into the impossible.',
    archetypeSkills: [
      { name: 'Alertness',   value: 50 },
      { name: 'Athletics',   value: 60 },
      { name: 'Drive',       value: 50 },
      { name: 'Firearms',    value: 60 },
      { name: 'Harangue',    value: 60 },
      { name: 'Insight',     value: 50 },
      { name: 'Law (Type)',  value: 40 },
      { name: 'Search',      value: 50 },
    ],
    optionalSkills: [
      { name: 'Disguise',             value: 50 },
      { name: 'Dodge',                value: 70 },
      { name: 'First Aid',            value: 50 },
      { name: 'Forensics',            value: 40 },
      { name: 'Melee Weapons',        value: 70 },
      { name: 'Persuade',             value: 60 },
      { name: 'Regional Lore (Type)', value: 40 },
      { name: 'Stealth',              value: 50 },
      { name: 'Technology Use',       value: 40 },
    ],
    optionalCount: 4,
    resources: 4,
    bonds: 3,
  },
  {
    id: 'librarian',
    name: 'Librarian / Archivist',
    ages: ['modern'],
    recommendedStats: ['INT'],
    description: 'Archivists who have catalogued books that should never have been written.',
    archetypeSkills: [
      { name: 'Administration', value: 60 },
      { name: 'Alertness',      value: 50 },
      { name: 'Appraise',       value: 50 },
      { name: 'Research',       value: 60 },
      { name: 'Search',         value: 50 },
      { name: 'Technology Use', value: 50 },
    ],
    optionalSkills: [
      { name: 'Anthropology',            value: 40 },
      { name: 'Archeology',              value: 40 },
      { name: 'Art (Type)',              value: 40 },
      { name: 'Foreign Language (Type)', value: 40 },
      { name: 'History',                 value: 50 },
      { name: 'Law (Type)',              value: 40 },
      { name: 'Occult',                  value: 50 },
      { name: 'Regional Lore (Type)',    value: 40 },
    ],
    optionalCount: 5,
    resources: 4,
    bonds: 3,
  },
  {
    id: 'researcher',
    name: 'Researcher / Scientist',
    ages: ['modern'],
    recommendedStats: ['INT'],
    description: 'Scientists whose commitment to data is tested by data that cannot be real.',
    archetypeSkills: [
      { name: 'Administration',  value: 50 },
      { name: 'Persuade',        value: 60 },
      { name: 'Research',        value: 70 },
      { name: 'Science (Type)',  value: 70 },
      { name: 'Search',          value: 60 },
      { name: 'Technology Use',  value: 40 },
    ],
    optionalSkills: [
      { name: 'Anthropology',             value: 40 },
      { name: 'Archeology',               value: 40 },
      { name: 'Art (Type)',               value: 40 },
      { name: 'Firearms',                 value: 60 },
      { name: 'Foreign Language (Type)',  value: 40 },
      { name: 'Heavy Machinery',          value: 50 },
      { name: 'Military Training (Type)', value: 40 },
      { name: 'Natural World',            value: 50 },
      { name: 'Psychoanalyze',            value: 50 },
      { name: 'Science (Type)',           value: 40 },
    ],
    optionalCount: 4,
    resources: 5,
    bonds: 2,
  },
  {
    id: 'technologist',
    name: 'Technologist',
    ages: ['modern'],
    recommendedStats: ['INT', 'POW'],
    description: 'Tech experts whose mastery of systems makes them dangerous to ancient forces.',
    archetypeSkills: [
      { name: 'Administration', value: 50 },
      { name: 'Alertness',      value: 50 },
      { name: 'Art (Type)',     value: 40 },
      { name: 'Insight',        value: 50 },
      { name: 'Persuade',       value: 50 },
      { name: 'Search',         value: 50 },
      { name: 'Technology Use', value: 80 },
    ],
    optionalSkills: [
      { name: 'Appraise',                value: 50 },
      { name: 'Craft (Type)',            value: 40 },
      { name: 'Firearms',                value: 60 },
      { name: 'Heavy Machinery',         value: 50 },
      { name: 'Military Training (Type)', value: 40 },
      { name: 'Navigate',                value: 50 },
      { name: 'Pilot (Type)',            value: 40 },
      { name: 'Research',                value: 50 },
    ],
    optionalCount: 4,
    resources: 4,
    bonds: 3,
  },
  {
    id: 'white_collar',
    name: 'White-Collar Worker',
    ages: ['modern'],
    recommendedStats: ['INT', 'CHA'],
    description: 'Office professionals who discover that the real conspiracies are far older.',
    archetypeSkills: [
      { name: 'Administration',  value: 60 },
      { name: 'Charm',           value: 50 },
      { name: 'Insight',         value: 50 },
      { name: 'Persuade',        value: 50 },
      { name: 'Research',        value: 40 },
      { name: 'Technology Use',  value: 60 },
    ],
    optionalSkills: [
      { name: 'Appraise',                value: 50 },
      { name: 'Art (Type)',              value: 40 },
      { name: 'First Aid',               value: 50 },
      { name: 'Foreign Language (Type)', value: 40 },
      { name: 'Harangue',                value: 50 },
      { name: 'History',                 value: 50 },
      { name: 'Military Training (Type)', value: 40 },
      { name: 'Occult',                  value: 50 },
    ],
    optionalCount: 4,
    resources: 5,
    bonds: 3,
  },
];

// ── Step config ───────────────────────────────────────────────

const STEPS = [
  { id: 1, label: 'Era',         title: 'Choose Your Era' },
  { id: 2, label: 'Attributes',  title: 'Roll Your Attributes' },
  { id: 3, label: 'Archetype',   title: 'Choose Your Archetype' },
  { id: 4, label: 'Points',      title: 'Distribute Your Points' },
  { id: 5, label: 'Motivations', title: 'Motivations & Gear' },
  { id: 6, label: 'Identity',    title: 'Forge Your Identity' },
];
